# version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipe
      - DB_USER=minh
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipe
      - POSTGRES_USER=minh
      - POSTGRES_PASSWORD=password

volumes:
    dev-db-data:

# docker-compose run --rm app sh -c "python manage.py test"
# docker-compose run --rm app sh -c "django-admin startproject app ." thêm chấm để cho folder vào folderfolder
# docker-compose run --rm app sh -c "flake8"
